image:
  registry: harbor.local:30002
  repository: harbor/grafana
  tag: latest
  pullPolicy: Always
  pullSecrets:
    - harbor-regcred

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

adminUser: admin
adminPassword: "Azerty77"

persistence:
  enabled: true
  type: pvc
  size: 2Gi
  accessModes:
    - ReadWriteOnce

initChownData:
  enabled: false

securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472

containerSecurityContext:
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

podAnnotations:
  vault.hashicorp.com/agent-inject: "true"
  vault.hashicorp.com/role: "grafana"

  vault.hashicorp.com/agent-inject-secret-admin_user: "secret/data/grafana/config"
  vault.hashicorp.com/agent-inject-template-admin_user: |
    {{- with secret "secret/data/grafana/config" -}}
    {{ .Data.data.username }}
    {{- end }}

  vault.hashicorp.com/agent-inject-secret-admin_password: "secret/data/grafana/config"
  vault.hashicorp.com/agent-inject-template-admin_password: |
    {{- with secret "secret/data/grafana/config" -}}
    {{ .Data.data.password }}
    {{- end }}
